"""BMI"""
def main():
    """BMI"""
    name_1 = str(input())
    weight_1 = float(input())
    tall_1 = float(input())
    name_2 = str(input())
    weight_2 = float(input())
    tall_2 = float(input())
    name_3 = str(input())
    weight_3 = float(input())
    tall_3 = float(input())
    name_4 = str(input())
    weight_4 = float(input())
    tall_4 = float(input())
    name_5 = str(input())
    weight_5 = float(input())
    tall_5 = float(input())
    result_1 = (weight_1/((tall_1 / 100)**2))
    result_2 = (weight_2/((tall_2 / 100)**2))
    result_3 = (weight_3/((tall_3 / 100)**2))
    result_4 = (weight_4/((tall_4 / 100)**2))
    result_5 = (weight_5/((tall_5 / 100)**2))
    print(name_1 + "'s  BMI = %.2f " % result_1)
    print(name_2 + "'s  BMI = %.2f " % result_2)
    print(name_3 + "'s  BMI = %.2f " % result_3)
    print(name_4 + "'s  BMI = %.2f " % result_4)
    print(name_5 + "'s  BMI = %.2f " % result_5)
main()
